import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main TODO projects sidebar
  todoSidebar: [
    "intro",
    "kun-app",
    "kun-youth",
    "current-power",
    "current-power-test",
  ],

  // Templates and guides sidebar
  templatesSidebar: [
    {
      type: "category",
      label: "📝 Project Templates",
      items: [
        {
          type: "autogenerated",
          dirName: "templates",
        },
      ],
      collapsible: true,
      collapsed: false,
    },
    {
      type: "category",
      label: "🛠️ Guides & Best Practices",
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
      collapsible: true,
      collapsed: false,
    },
  ],
};

export default sidebars;
